<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
    <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
    <?php
    $link = $_SERVER['REQUEST_URI'];
    switch ($link) {
        case '/FP_DWO_KELOMPOK_11/index.php':
            echo '<li class="nav-item">';
            echo '<a href="index.php" class="nav-link active">';
            echo '<i class="nav-icon fas fa-tachometer-alt"></i>';
            echo '<p>Dashboard</p>';
            echo '</a>';
            echo '<li class="nav-header">CHART MENU</li>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_sales.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>FACT SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_purchasing.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>FACT PURCHASING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="customer.php" class="nav-link">';
            echo '<i class="nav-icon far fa-calendar-alt"></i>';
            echo '<p>CUSTOMER</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="employee.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>EMPLOYEE</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="product.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>PRODUCT</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="sales.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="shipping.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>SHIPPING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="vendor.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>VENDOR</p>';
            echo '<a>';
            echo '</li>';
            break;
        case '/FP_DWO_KELOMPOK_11/fact_sales.php':
            echo '<li class="nav-item">';
            echo '<a href="index.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-tachometer-alt"></i>';
            echo '<p>Dashboard</p>';
            echo '</a>';
            echo '<li class="nav-header">CHART MENU</li>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_sales.php" class="nav-link active">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>FACT SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_purchasing.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>FACT PURCHASING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="customer.php" class="nav-link">';
            echo '<i class="nav-icon far fa-calendar-alt"></i>';
            echo '<p>CUSTOMER</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="employee.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>EMPLOYEE</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="product.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>PRODUCT</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="sales.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="shipping.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>SHIPPING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="vendor.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>VENDOR</p>';
            echo '<a>';
            echo '</li>';
            break;
        case '/FP_DWO_KELOMPOK_11/fact_purchasing.php':
            echo '<li class="nav-item">';
            echo '<a href="index.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-tachometer-alt"></i>';
            echo '<p>Dashboard</p>';
            echo '</a>';
            echo '<li class="nav-header">CHART MENU</li>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_sales.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>FACT SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_purchasing.php" class="nav-link active">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>FACT PURCHASING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="customer.php" class="nav-link">';
            echo '<i class="nav-icon far fa-calendar-alt"></i>';
            echo '<p>CUSTOMER</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="employee.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>EMPLOYEE</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="product.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>PRODUCT</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="sales.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="shipping.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>SHIPPING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="vendor.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>VENDOR</p>';
            echo '<a>';
            echo '</li>';
            break;
        case '/FP_DWO_KELOMPOK_11/customer.php':
            echo '<li class="nav-item">';
            echo '<a href="index.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-tachometer-alt"></i>';
            echo '<p>Dashboard</p>';
            echo '</a>';
            echo '<li class="nav-header">CHART MENU</li>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_sales.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>FACT SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_purchasing.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>FACT PURCHASING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="customer.php" class="nav-link active">';
            echo '<i class="nav-icon far fa-calendar-alt"></i>';
            echo '<p>CUSTOMER</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="employee.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>EMPLOYEE</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="product.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>PRODUCT</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="sales.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="shipping.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>SHIPPING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="vendor.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>VENDOR</p>';
            echo '<a>';
            echo '</li>';
            break;
        case '/FP_DWO_KELOMPOK_11/employee.php':
            echo '<li class="nav-item">';
            echo '<a href="index.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-tachometer-alt"></i>';
            echo '<p>Dashboard</p>';
            echo '</a>';
            echo '<li class="nav-header">CHART MENU</li>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_sales.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>FACT SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_purchasing.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>FACT PURCHASING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="customer.php" class="nav-link">';
            echo '<i class="nav-icon far fa-calendar-alt"></i>';
            echo '<p>CUSTOMER</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="employee.php" class="nav-link active">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>EMPLOYEE</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="product.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>PRODUCT</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="sales.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="shipping.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>SHIPPING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="vendor.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>VENDOR</p>';
            echo '<a>';
            echo '</li>';
            break;
        case '/FP_DWO_KELOMPOK_11/product.php':
            echo '<li class="nav-item">';
            echo '<a href="index.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-tachometer-alt"></i>';
            echo '<p>Dashboard</p>';
            echo '</a>';
            echo '<li class="nav-header">CHART MENU</li>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_sales.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>FACT SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_purchasing.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>FACT PURCHASING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="customer.php" class="nav-link">';
            echo '<i class="nav-icon far fa-calendar-alt"></i>';
            echo '<p>CUSTOMER</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="employee.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>EMPLOYEE</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="product.php" class="nav-link active">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>PRODUCT</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="sales.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="shipping.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>SHIPPING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="vendor.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>VENDOR</p>';
            echo '<a>';
            echo '</li>';
            break;
        case '/FP_DWO_KELOMPOK_11/sales.php':
            echo '<li class="nav-item">';
            echo '<a href="index.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-tachometer-alt"></i>';
            echo '<p>Dashboard</p>';
            echo '</a>';
            echo '<li class="nav-header">CHART MENU</li>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_sales.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>FACT SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_purchasing.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>FACT PURCHASING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="customer.php" class="nav-link">';
            echo '<i class="nav-icon far fa-calendar-alt"></i>';
            echo '<p>CUSTOMER</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="employee.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>EMPLOYEE</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="product.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>PRODUCT</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="sales.php" class="nav-link active">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="shipping.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>SHIPPING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="vendor.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>VENDOR</p>';
            echo '<a>';
            echo '</li>';
            break;
        case '/FP_DWO_KELOMPOK_11/shipping.php':
            echo '<li class="nav-item">';
            echo '<a href="index.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-tachometer-alt"></i>';
            echo '<p>Dashboard</p>';
            echo '</a>';
            echo '<li class="nav-header">CHART MENU</li>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_sales.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>FACT SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_purchasing.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>FACT PURCHASING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="customer.php" class="nav-link">';
            echo '<i class="nav-icon far fa-calendar-alt"></i>';
            echo '<p>CUSTOMER</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="employee.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>EMPLOYEE</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="product.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>PRODUCT</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="sales.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="shipping.php" class="nav-link active">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>SHIPPING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="vendor.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>VENDOR</p>';
            echo '<a>';
            echo '</li>';
            break;
        case '/FP_DWO_KELOMPOK_11/vendor.php':
            echo '<li class="nav-item">';
            echo '<a href="index.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-tachometer-alt"></i>';
            echo '<p>Dashboard</p>';
            echo '</a>';
            echo '<li class="nav-header">CHART MENU</li>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_sales.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>FACT SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_purchasing.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>FACT PURCHASING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="customer.php" class="nav-link">';
            echo '<i class="nav-icon far fa-calendar-alt"></i>';
            echo '<p>CUSTOMER</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="employee.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>EMPLOYEE</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="product.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>PRODUCT</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="sales.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="shipping.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>SHIPPING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="vendor.php" class="nav-link active">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>VENDOR</p>';
            echo '<a>';
            echo '</li>';
            break;
        default:
            echo '<li class="nav-item">';
            echo '<a href="index.php" class="nav-link">';
            echo '<i class="nav-icon fas fa-tachometer-alt"></i>';
            echo '<p>Dashboard</p>';
            echo '</a>';
            echo '<li class="nav-header">CHART MENU</li>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_sales.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>FACT SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="fact_purchasing.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>FACT PURCHASING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="customer.php" class="nav-link">';
            echo '<i class="nav-icon far fa-calendar-alt"></i>';
            echo '<p>CUSTOMER</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="employee.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>EMPLOYEE</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="product.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>PRODUCT</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="sales.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>SALES</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="shipping.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>SHIPPING</p>';
            echo '<a>';
            echo '</li>';
            echo '<li class="nav-item">';
            echo '<a href="vendor.php" class="nav-link">';
            echo '<i class="nav-icon far fa-image"></i>';
            echo '<p>VENDOR</p>';
            echo '<a>';
            echo '</li>';
            break;
    }
    ?>
</ul>